application: backend-150118
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest
